version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "steve-auth"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dumyiijsqf99"
s3_prefix = "steve-auth"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
